### ISSUE TITLE
Explicit config over implicit env variables

### ISSUE THREAD

**Issue by michavie** [Itheum/sdk-mx-data-nft#17]
Currently, the SDK relies on environment variables being set that can only be inferred by reading the source code.

Ideally, developers are required to set the config on SDK init and there is validation for the configuration values.

As an example, when attempting to mint a DataNFT, these env variables have to be implicitly added:
```
REACT_APP_ENV_NFT_STORAGE_KEY
REACT_APP_ENV_DATADEX_API
REACT_APP_ENV_DATAMARSHAL_API
```

Suggestions for a better DX:
- Require config to be set on SDK initialization
- Add validation for config values
- Add detailed error messages for optional values (e.g., it currently executes fetch() without url set, leading to confusing error messages)
- Set default overridable config values for e.g. the Marshal service url and the Anti-spam fee
- Remove dotenv npm dependency entirely to keep things clean

**Comment by newbreedofgeek** [comment]
@michavie tnx for raising this. 

This is indeed an issue we picked up last week as well and are fixing it. ETA sometime this week.

**Comment by newbreedofgeek** [comment]
Most of the above were fixed.

These items are moved to a seperate ticket.

`Add validation for config values
Add detailed error messages for optional values (e.g., it currently executes fetch() without url set, leading to confusing error messages)`

**Comment by michavie** [comment]
Awesome @newbreedofgeek!

Closing this
