### ISSUE TITLE
Refactor validateSpecificParams* methods and add tests

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/sdk-mx-data-nft#33]
- As per here https://github.com/Itheum/sdk-mx-data-nft/pull/31#discussion_r1319907153 and other recommendation in this thread, let's refactor the validateSpecificParams* methods
- Let's also add some basic unit tests for validateSpecificParams* methods

**Comment by bucurdavid** [comment]
Solved.Closing.
