### ISSUE TITLE
Automate NPM deployements

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/sdk-mx-data-nft#34]
- automate NPM deployment when checked into MAIN
- but only after we confirm things like - has version been upgraded from what is in package.json and what is live on npm, has tests passed, has docs being upgraded etc

**Comment by bucurdavid** [comment]
The workflow added is triggered manually not on when checked into MAIN.

**Comment by bucurdavid** [comment]
Solved.Closing
