### ISSUE TITLE
v2 - updates and follows needed

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/sdk-mx-data-nft#55]
Some items to follow up and update... as observed when testing V2 via the SDK

**Comment by newbreedofgeek** [comment]
nftMinter.initializeContract documentation seems incomplete.

e.g. claims address for royalties param is not appearing in the documentation for the params

<img width="1475" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/127384e4-3de8-4370-912b-5bbc7e846d19">

**Comment by newbreedofgeek** [comment]
nftMinter.initializeContract's `mintLimit` param  [(seconds)- The mint limit between mints ]- should this be called "secsBetweenMints"? or something that aligns better?

**Comment by newbreedofgeek** [comment]
Does nftMinter.initializeContract have a MAX limit in the collection? ie. 10k. Is this needed?

**Comment by newbreedofgeek** [comment]
- I setup a new minter, but when I called `initializeContract` I got a `TX Success`, but onchain it seemed to fail as no token was issued. See this TX : https://devnet-explorer.multiversx.com/transactions/dca7412ded69fcff3f905b05d41ab46f017ba9c2ccc70891a4fc33dab6b67c7a#d938fb9558c4c62f36f5a5bf3b1fcb69e2eec4ab303e2b8c864db4c8062b711e

- I then called `await nftMinter.viewContractConfiguration();`, but I got the following error. Does this error make sense?

<img width="483" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/30093054-d391-4907-a69a-f6c1da4f69e5">

**Comment by newbreedofgeek** [comment]
In the docs, for the nftMinter and sftMinter, for tokenName... just write `the name of the Data NFT. Between 3 and 20 alphanumeric characters, no spaces.`

<img width="1118" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/15eba222-de68-4d92-8715-b239fd867638">

**Comment by newbreedofgeek** [comment]
in the docs, for nftMinter and sftMinter, the antiSpamTax is in different places. Need to align it, maybe the best is the pattern in nftMinter.

https://itheum.github.io/sdk-mx-data-nft/classes/SftMinter.html#mint
https://itheum.github.io/sdk-mx-data-nft/classes/NftMinter.html#mint

<img width="979" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/69f2f85c-be1f-4f8f-992a-038f1817ffe1">

<img width="956" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/ffd40756-9464-4ed0-a9dd-cf2741f7f08a">

**Comment by newbreedofgeek** [comment]
in docs, for both the nft and sft minter we have "pauseCollection" and "unpauseCollection".

This is the "freeze" collection right? once we clarify, we need to update the docs to be more descriptive

<img width="666" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/fd940131-b53a-4ba7-84d9-16621d001ec8">

**Comment by newbreedofgeek** [comment]
in SDK, for both nt and sft minter, how do you remove someone from the whitelist?

If it's possible, we need to update docs and/or SDK to allow this.

<img width="684" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/25aaf4d6-0294-4f46-8cc3-48e6a6f01e69">

**Comment by newbreedofgeek** [comment]
on the SDK/docs, 

- can https://itheum.github.io/sdk-mx-data-nft/classes/DataNft.html#ownedByAddress support a list of token IDs, so we can show both SFT and NFT collections?
- we should update the docs to remove "Data NFT-FT" and add "Data NFT" as it supports both types.

<img width="934" alt="image" src="https://github.com/Itheum/sdk-mx-data-nft/assets/743169/31ff5067-3bd3-4207-94aa-1e244b3bbfbc">

**Comment by bucurdavid** [comment]
With the successive updates to the SDK, it seems appropriate to consider this issue resolved.
CC: @newbreedofgeek

**Comment by newbreedofgeek** [comment]
closing
