### ISSUE TITLE
Swap out the Generate route to V2 to enable Data NFT minting watermarks + Use the new Data Marshal "router" URL

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/sdk-mx-data-nft#56]
- We will use a new Data Marshal Generate route that does "watermark" protection on Data NFTs
- We will also use a new Data Marshal "router" URL in the mint form that allows for us to swap out to the new Data Marshal when it's available.

**Comment by damienen** [comment]
Merged to prod. Closing
