### ISSUE TITLE
createFromApiResponse and createFromApiResponseBulk can be merged

### ISSUE THREAD

**Issue by damienen** [Itheum/sdk-mx-data-nft#8]
createFromApiResponse and createFromApiResponseBulk can be merged without any breaking changes to createFromApiResponse

**Comment by newbreedofgeek** [comment]
@bucurdavid I'm not sure if this was done? if fixed and published to NPM... then please close ticket.

**Comment by bucurdavid** [comment]
@newbreedofgeek  Fixed in commit: 9977923

**Comment by bucurdavid** [comment]
Closing.Fixed in commit 9977923
