### ISSUE TITLE
Roll out pepe's fix to Data NFT SDK

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/sdk-mx-data-nft#95]

**Comment by damienen** [comment]
Fixed in this PR: https://github.com/Itheum/sdk-mx-data-nft/pull/92

**Comment by damienen** [comment]
The only thing that might be missing is allowing users to override the marshal as well if they want to.

**Comment by damienen** [comment]
One more thing as we discussed in DMs, @bucurdavid : 

1. Semantic bot push should happen on develop (and maybe create a PR towards main that we can manually approve? but this is not obligatory)
2. Push to npm should be able to be done from main branch without doing a push to main

**Comment by damienen** [comment]
Alright. We will push out the semantic releasing and we will do just auto npm releases once some new commits goes to main

**Comment by damienen** [comment]
Solved. Closing.
